server:
  port: 8889
spring:
  profiles:
    active: native
  application:
    name: confi-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

