apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: infrastructure
data:
  spring.profiles.active: "prod"
  config.git.uri: "https://github.com/your-org/config-repo.git"
  application.yml: |
    server:
      port: 8222
    spring:
      cloud:
        config:
          server:
            git:
              default-label: main