apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deploy
  namespace: fintech
  labels:
    app: config-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: public.ecr.aws/z1z0w2y6/config-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8889
              name: http
          envFrom:
            - configMapRef:
                name: config-service-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "native"
          resources:
            requests:
              memory: "400Mi"
              cpu: "200m"
            limits:
              memory: "800Mi"
              cpu: "400m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8889
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8889
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: config-volume
              mountPath: /app/configurations
      volumes:
        - name: config-volume
          configMap:
            name: service-configurations
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000