apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ${process.env.ECR_REPO}/config-server:latest
          ports:
            - containerPort: 8222
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8222
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: config-server-config
                  key: spring.profiles.active
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              valueFrom:
                configMapKeyRef:
                  name: config-server-config
                  key: config.git.uri