apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: infrastructure
spec:
  type: ClusterIP
  ports:
    - port: 8222
      targetPort: 8222
      protocol: TCP
  selector:
    app: config-server