apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: fintech
  labels:
    app: config-service
spec:
  type: LoadBalancer
  ports:
    - port: 8889
      targetPort: 8889
      protocol: TCP
      name: http
  type: ClusterIP
  selector:
    app: config-service
