server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE # Load-balanced URI
          predicates:
            - Path=/api/users/** # Ensure spacing and correct predicate format

        - id: image-service
          uri: lb://USER-SERVICE # Assuming image endpoint is served by user-service
          predicates:
            - Path=/users/public/images/**

        - id: wallet-service
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/api/wallets/**

        - id: wallet-service-currency
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/api/currencies/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transaction/** # Corrected spacing and added missing "/*" for full path match
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
  instance:
    preferIpAddress: true  # Register IP address instead of hostname
