server:
  port: 8085 # Notification microservice port

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my-database-instance.c122egeymo28.us-east-1.rds.amazonaws.com:3306/notification_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
