server:
  port: 8599


spring:
  datasource:
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transaction_service_db  # Ensure this is your actual database name
  jpa:
    hibernate:
      ddl-auto: update                             # Use 'update' for schema updates without dropping
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
  instance:
    preferIpAddress: true  # Register IP address instead of hostname
