server:
  port: 8099

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wallet_service_db  # Ensure this is your actual database name
    username: postgres                             # Database username
    password: password                             # Database password
  jpa:
    hibernate:
      ddl-auto: update                             # Use 'update' for schema updates without dropping
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
  instance:
    preferIpAddress: true  # Register IP address instead of hostname
